services:
  # PHP + Apache service
  api:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: ${API_CONTAINER_NAME}
    volumes:
      - ./api:/var/www/html
      - ./.docker/apache/site.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "${API_PORT}:80"
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_DATABASE}

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: ${DB_CONTAINER_NAME}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  # Angular Frontend Service
  frontend:
    build:
      context: ./.docker/angular
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: ${FRONTEND_CONTAINER_NAME}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT}:4200"

volumes:
  mysql_data: 